# Cgeneral configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development server configuration  
development:
  <<: *default
  database: AppTClone_development

# test server configuration
test:
  <<: *default
  database: AppTClone_test

#   production server configuration
production:
  <<: *default
  database: AppTClone_production
  username: AppTClone
  password: <%= ENV['APPTCLONE_DATABASE_PASSWORD'] %>
